Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from pastis import dispersion
from sklearn.externals.joblib import Memory

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-a71c76d0bad7>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfrom[0m [0mpastis[0m [0;32mimport[0m [0mdispersion[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mexternals[0m[0;34m.[0m[0mjoblib[0m [0;32mimport[0m [0mMemory[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/pastis/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mconfig[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mfrom[0m [0;34m.[0m[0mio[0m [0;32mimport[0m [0mwrite[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mexternals[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mfastio[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0malgorithms[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/pastis/externals/__init__.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0miced[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mwarnings[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m warnings.warn(
[1;32m      4[0m     [0;34m"This module is deprecated. Please use and install iced directly."[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     DeprecationWarning) 

[0;32m/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/pastis/externals/iced/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mfilter[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mio[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mdatasets[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0m__version__[0m [0;34m=[0m [0;34m"0.5.2"[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/pastis/externals/iced/datasets/__init__.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0;34m.[0m[0mbase[0m [0;32mimport[0m [0mclear_data_home[0m[0;34m,[0m [0mget_data_home[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0;34m.[0m[0mbase[0m [0;32mimport[0m [0mload_sample_yeast[0m[0;34m,[0m [0mload_sample_cancer[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/pastisnb/lib/python3.9/site-packages/pastis/externals/iced/datasets/base.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0;32mimport[0m [0mshutil[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;34m[0m[0m
[0;32m----> 7[0;31m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;32mfrom[0m [0;34m.[0m[0;34m.[0m [0;32mimport[0m [0mio[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

